config/routes.rb
Rails.application.routes.draw do
		get 'categories/check_name_present'
		get 'articles/check_name_present'

  devise_for :users
	resources :reviews
	resources :categories
	resources :articles
	get 'say/goodbye'
	get 'say/hello'
	root 'say#hello'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
validates_presence_of :title, :body, :category_id, :publish_date, :feature_image_url
validates_length_of :body, minimum: 5
validate :publish_date_is_not_greater_than_todays_date
belongs_to :category
belongs_to :user
has_many :reviews
private

def publish_date_is_not_greater_than_todays_date
	if (publish_date > Date.today + 30.days)
		errors.add(:publish_date, 'must not be greater than 1 month')
	end

end	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
load_and_authorize_resource
def index
	@articles = Article.paginate(:page => params[:page], :per_page => 6)
	@article = Article.new
	@category = Category.new
end
def new
	@article = Article.new
end
def create
	@article = Article.new(article_params)
	@article.user_id = current_user.id
	if @article.publish_date <= Date.today
		@article.is_published = true
	else
		@article.publish_date > Date.today
		@article.is_published = false
	end
	if @article.save
		redirect_to articles_path(@article.id), notice: "Article was successfully created"
	else
		render action: 'new'
end
end
def show 
	@article = Article.find(params[:id])
	@review = Review.new
end
def edit
	@article = Article.find(params[:id])
end
def update
	@article = Article.find(params[:id])
	@article.user_id = current_user.id
	if @article.update_attributes(article_params)
		redirect_to articles_path(@article.id), notice: "The article was successfully updated"
	else
		render action:"edit"
	end
end
def destroy
	@article = Article.find(params[:id])
	@article.destroy
		redirect_to articles_path, notice: "The article was successfully deleted"	
end

def check_name_present
		@article = Article.find_by(title: params[:title])
	    render json: @article.nil? ? {'msg': 'can be used'} : {'msg': 'already taken'}   
	end

private

def article_params
	params[:article].permit(:user_id, :title, :body ,:category_id, :publish_date, :feature_image_url, :cover, :is_published)
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

<% if @article.errors.any? %>
<h3>These errors prohibited the form from being saved</h3>
<ul>
	<% @article.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>
<label for="article_category_id">Category : </label> <br/>
<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %> <br/>

<label for="article_title">Title : </label>  <br/>
<%= f.text_field :title, placeholder: "Enter title" %> <span id="nameMsg"></span> <br/>

<label for="article_body">Body : </label> <br/>
<%= f.text_area :body, placeholder: "Enter description" %>  <span id="bodyMsg"></span><br/>

<label for="article_publish_date">Publish Date : </label> <br/>
<%= f.date_select :publish_date, start_year: Date.today.year, end_year: Date.today.year + 1 %> <br/>

<label for="article_feature_image_url">Image : </label> <br/>
<%= f.text_field :feature_image_url %> <br/>

<%= f.submit %>

<% end %>

<script>
	var nameHandle = document.getElementById('article_title');
	var nameMsgHandle = document.getElementById('nameMsg');

	nameHandle.addEventListener('focus', function(){
		nameMsgHandle.innerHTML = "Enter the article title";
	}, false)

	nameHandle.addEventListener('blur', function(){
		if (nameHandle.value === ""){
			nameErrorMsgHandle.innerHTML = "can't be blank"
		}
		else{
  var xhr = new XMLHttpRequest();
xhr.open('GET','/articles/check_name_present?title=' + nameHandle.value, true)
  xhr.onreadystatechange = function(){
    if(xhr.readyState === 4 && xhr.status === 200){
      var response = JSON.parse(xhr.responseText);
      nameMsgHandle.innerHTML = response.msg;
    }
  }
  xhr.send()
}
  }, false);
	nameHandle.addEventListener('focus', function(){
  nameMsgHandle.innerHTML = "";
},false);


	nameHandle.addEventListener('blur', function(){
		if(nameHandle.value == ""){
			nameMsgHandle.innerHTML = "can't be blank";
		}else {
			nameMsgHandle.innerHTML = "";
		}
	}, false);


	var bodyHandle = document.getElementById('article_body');
	var bodyMsgHandle = document.getElementById('bodyMsg');

	bodyHandle.addEventListener('focus', function(){
		bodyMsgHandle.innerHTML = "Enter the article description";
	}, false)


	bodyHandle.addEventListener('blur', function(){
		if(bodyHandle.value == ""){
			bodyMsgHandle.innerHTML = "can't be blank";
		}else {
			bodyMsgHandle.innerHTML = "";
		}
	}, false);

</script>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="row">
<div class="col-lg-4">
	<div class="card my-4">
    		<h5 class="card-header"> <%=link_to "#{Category}", categories_path%></h5>
    		<div class="card-body">
    			<div class="row">
    				<div class="col-lg-6">
    					<ul class="list-unstyled mb-0">
    						
    						<% Category.all.each do |category| %>
    						<li><%= link_to category.name, category %></li>
    						<% end %>
    						</ul>
    					</div>
    				</div>
    			</div>
    		</div>
    		<div class="col-md-4">
				<button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModal">
				<h2>Add Category</h2>
				</button>
			</div>
    		<div class="card my-4">
    		<div class="col-md-4">
				<h3>Add Article</h3>
				<%= render 'form', article: @article%>
			</div>
			</div>
</div>
<div class="col-lg-8">
	<h1 class="display-6">Listing Articles
		<small>(<%= @articles.count %>)</small>
	</h1></br>
	<div class="row">
	<% @articles.each do |article|%>
	<!-- <div class="col-lg-4"> -->
		
		<!-- Blog Post -->
		<div class="col-lg-4 col-md-6 mb-4">
			<%= image_tag(article.feature_image_url, size: "300x150", class: "card-img-top" )%>
			<div class="card-body">
				<h2 class="card-title"><%= article.title%></h2>
				<p class="card-text"><%= article.body.truncate(100)%></p>
				<%= link_to "Read More", article, class: 'btn btn-primary' %>
			</div>
			<div class="card-footer text-muted">
				Posted on <%= article.publish_date.strftime("%B %d %Y") %> in
				<%= link_to article.category.name, article.category %>
			</div>
		</div>
		<!-- Pagination -->
          <!-- <ul class="pagination justify-content-center mb-4">
            <li class="page-item">
              <a class="page-link" href="#">&larr; Older</a>
            </li>
            <li class="page-item disabled">
              <a class="page-link" href="#">Newer &rarr;</a>
            </li>
        </ul> -->
    <!-- </div> -->
    <%end%>
    </div>
</div>
</div>
<!-- /.row -->
<%#= will_paginate @articles, renderer: BootstrapPagination::Rails %>
<%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Add Category</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<%= render '/categories/form', category: @category %>
					</div>

				</div>
			</div>
</div>
<!-- 
<h1>Listing Articles (<%= @articles.length%>)</h1>
<%# if @articles.empty? %>
	<p>No Articles Found</p>
<%# else %>
	<ol>
		<%# @articles.each do|article| %>
		 <%# if article.is_published == true 
			# || article.is_published <=>  Date.today 
			%>
			<li>
					<%# if !article.category.nil? %>
						<%#= article.category.name %>
					<%# end %>
				- <%#= link_to article.title, article_path(article.id) %>  - <%#= article.publish_date%>
			</li>
			<%# end %>
		<%# end %>
	</ol>
<%# end %>
<%# if (user_signed_in?) && (can? :create, Article.new) %>
<%#= link_to "Add Articles", new_article_path%>
<%# end %> -->

app/views/articles/new.html.erb
<h2>Add Article</h2>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row">

	<!-- Post Content Column -->
	<div class="col-lg-8">

		<!-- Title -->
		<h1 class="mt-4"><%= @article.title%></h1>

		<!-- Author -->
		<p class="lead">
			in
			<%= link_to @article.category.name, @article.category%>
		</p>

		<hr>

		<!-- Date/Time -->
		<p>Posted on <%= @article.publish_date.strftime("%B %d %Y %H:%M %p")%></p>

		<hr>

		<!-- Preview Image -->
		<!-- <img class="img-fluid rounded" src="@article.feature_image_url" alt=""> -->
		<%= image_tag(@article.feature_image_url, size: "900x300", class: "img-fluid rounded" )%>

		<hr>

		<!-- Post Content -->
		<p><h4>Description - </h4><%= raw(@article.body) %></p>

		<!-- Comments Form -->
		<div class="card my-4">
			<h5 class="card-header">Leave a Comment:</h5>
			<div class="card-body">

				<%= form_for @review do |f|%>
				<%= f.hidden_field :article_id , value: @article.id%><br/>
				<div class="form-group">
					<%= f.text_area :body, class: "form-control"%>
				</div>

				<label for ="review_rating"> Rating :</label> <br/>
				<%= f.radio_button :rating, 1 %> 1
				<%= f.radio_button :rating, 2 %> 2
				<%= f.radio_button :rating, 3 %> 3
				<%= f.radio_button :rating, 4 %> 4
				<%= f.radio_button :rating, 5 %> 5 <br/>
				<%= f.submit "Add Comment", class: "btn btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>


	<!-- Sidebar Widgets Column -->
	<div class="col-md-4">

		<!-- Search Widget -->
		<div class="card my-4">
			<h5 class="card-header">Reviews</h5>
			<div class="card-body">
				<% @article.reviews.each do |review|%>
		<div class="media mb-4">
			<img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
			<div class="media-body">
				<h5 class="mt-0"><%= review.user.try(:email)%></h5>
				<%= review.body%>
				<%= review.rating%>
			</div>
		</div>
		<%end%>
			</div>
		</div>		
	</div>
</div>
      <!-- /.row -->











<!-- 
<h2><%= @article.title %></h2>
<p><% if (user_signed_in?) && (can? :create, @article) %><%= link_to "edit", edit_article_path(@article.id) %> | <%= link_to"delete", article_path(@article.id), method: :delete, data: {confirm: "Are you sure? "} %><% end %> </p> 

<% if !@article.category.nil? %>
<%= link_to @article.category.name, category_path(@article.category_id) %>
<% end %> <br/>

<p> Description - <%= @article.body %></p>
<p> Date of publish - (<%= @article.publish_date %>)</p>
<p><%= image_tag(@article.feature_image_url, size: "700x300") %></p>
<%= link_to "Articles list",articles_path %>


<% if @article.reviews.empty? %>
<p>No reviews found. Be the first one to review.</p>
<% else %>
<h3> Listing Comments </h3>
<ol>
	<% @article.reviews.each do |review| %>
	<li>
		<%= review.body %> - (<%= review.rating %>) - <%= review.user_id %><p><% if (user_signed_in?) %><%= link_to "edit", edit_review_path(review.id) %> | <%= link_to "destroy", review_path(review.id),method: :delete, data: {confirm: "Are you sure you want to delete this review"} %><% end %> </p> 
	</li>
	<% end %>
</ol>
<% end %>

<h3>Add your comment</h3>
<%= form_for @review do |f| %>

<label for="review_body"> Body </label> <br/>
<%= f.text_area :body %> <br/>

<%= f.hidden_field :article_id, value: @article.id %>

<br/>
<label> Rating </label> <br/>
<%= f.radio_button :rating, 1 %> 1
<%= f.radio_button :rating, 2 %> 2
<%= f.radio_button :rating, 3 %> 3
<%= f.radio_button :rating, 4 %> 4
<%= f.radio_button :rating, 5 %> 5 <br/>
<%= f.submit "create" %>
<% end %> -->