config/routes.rb
Rails.application.routes.draw do
		get 'categories/check_name_present'
		get 'articles/check_name_present'

  devise_for :users
	resources :reviews
	resources :categories
	resources :articles
	get 'say/goodbye'
	get 'say/hello'
	root 'say#hello'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
validates_presence_of :name, :description
validates_uniqueness_of :name
has_many :articles
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_action :authenticate_user!, except: [:index, :show]
	load_and_authorize_resource

	def index
		@categories = Category.all
	end
	def new
		@category = Category.new
	end
	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to categories_path(@category.id), notice: "The category was successfully updated"
		else
			render action: 'new'
		end
	end
	def show
		@category = Category.find(params[:id])
	end
	def edit
		@category = Category.find(params[:id])
	end
	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(category_params)
			redirect_to categories_path(@category.id), notice: "The category was successfully updated"
		else
			render action: "edit"
		end
	end
	def destroy
		@category = Category.find(params[:id])
		@category.destroy
			redirect_to categories_path, notice: "The category was successfully updated"
	end

	def check_name_present
		category = Category.find_by(name: params[:name])
	    render json: category.nil? ? {'msg': 'can be used'} : {'msg': 'already taken'}   
	end

	private

	def category_params
		params[:category].permit(:name, :description)
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

<% if @category.errors.any? %>
<h3>These errors prohibited the form from being saved</h3>
<ul>
	<% @category.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<label for="category_name"> Name : </label> <br/>
<%= f.text_field :name, placeholder: "Enter name" %> <span id="nameMsg"></span><br/>

<label for="category_description"> Description : </label> <br/>
<%= f.text_area :description, placeholder: "Enter description" %> <span id="bodyMsg"></span><br/>


<%= f.submit %>

<% end %>

<script>
	var nameHandle = document.getElementById('category_name');
	var nameMsgHandle = document.getElementById('nameMsg');

	nameHandle.addEventListener('focus', function(){
		nameMsgHandle.innerHTML = "Enter the category name";
	}, false)

	nameHandle.addEventListener('blur', function(){
  var xhr = new XMLHttpRequest();
xhr.open('GET','/categories/check_name_present?name=' + nameHandle.value, true)
  xhr.onreadystatechange = function(){
    if(xhr.readyState === 4 && xhr.status === 200){
      var response = JSON.parse(xhr.responseText);
      nameMsgHandle.innerHTML = response.msg;
    }
  }
  xhr.send()
  }, false);

	nameHandle.addEventListener('blur', function(){
		if(nameHandle.value == ""){
			nameMsgHandle.innerHTML = "can't be blank";
		}else {
			nameMsgHandle.innerHTML = "";
		}
	}, false);

	var bodyHandle = document.getElementById('category_description');
	var bodyMsgHandle = document.getElementById('bodyMsg');

	bodyHandle.addEventListener('focus', function(){
		bodyMsgHandle.innerHTML = "Enter the category description";
	}, false)


	bodyHandle.addEventListener('blur', function(){
		if(bodyHandle.value == ""){
			bodyMsgHandle.innerHTML = "can't be blank";
		}else {
			bodyMsgHandle.innerHTML = "";
		}
	}, false);

  
// var nameHandle = document.getElementById('category_name');
// 	var nameMsgHandle = document.getElementById('nameMsg');

// nameHandle.addEventListener('blur', function(){
//   var xhr = new XMLHttpRequest();
//   xhr.open('GET','/categories/check_name_present?name=' + nameHandle.value, true)
//   xhr.onreadystatechange = function(){
//     if(xhr.readyState === 4 && xhr.status === 200){
//       var response = JSON.parse(xhr.responseText);
//       nameMsgHandle.innerHTML = response.msg;
//     }
//   }
//   xhr.send()
//   }, false);

nameHandle.addEventListener('focus', function(){
  nameMsgHandle.innerHTML = "";
},false);







</script>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="display-5">Listing Categories
			<small>(<%= @categories.count %>)</small>
		</h1>
<div class="row">
	<!-- Blog Entries Column -->
	<div class="row md-8">


		<% @categories.each do |category|%>
		<!-- Blog Post -->
			<div class="mb-4">
				<%#= image_tag(article.feature_image_url, size: "750x300", class: "card-img-top" )%>
				<div class="card-body">
					<h2 class="card-title"><%= link_to category.name, category_path(category.id) %> - (<%= category.articles.count %>)</h2>
					<!-- <p class="card-text"><%#= category.description.truncate(100)%></p> -->
					<%= link_to "Read More", category, class: 'btn btn-primary' %>
				</div>
		            <!-- <div class="card-footer text-muted">
		              Posted on <%#= category.publish_date.strftime("%B %d %Y") %> by
		              <%#= link_to article.category.name, article.category %>
		          </div> -->
		    </div>
	    <%end%>
	    </div>
</div>
<ul class="pagination justify-content-center mb-4">
	      	<li class="page-item">
	      		<a class="page-link" href="#">&larr; Older</a>
	      	</li>
	      	<li class="page-item disabled">
	      		<a class="page-link" href="#">Newer &rarr;</a>
	      	</li>
	      </ul>

	  <!-- Sidebar Widgets Column -->
	  <!-- <div class="col-md-4"> -->

	  	<!-- Search Widget -->
          <!-- <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
        </div> -->


        <!-- Side Widget -->
          <!-- <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
        </div> -->

    <!-- </div> -->

<!-- </div> -->
<!-- /.row -->

app/views/categories/new.html.erb
<h2>Add Category</h2>
<%= render 'form' %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2><p><% if (user_signed_in?) && (can? :create, @category) %>(<%= link_to "edit", edit_category_path(@category.id) %> | <%= link_to "delete", category_path(@category.id), method: :delete, data: {confirm: "Are you sure? "}%>) <% end %></p>
<br>
<h4>List of articles :</h4>
<%#=@category.description %> 
<ul>  
	<% Article.all.find_all{|p| p.category_id==@category.id}.each do|article|%>
	<li><p><%= article.title %></p></li>
	<% end %>
</ul>
<br> 
<%= link_to "Categories list",categories_path %>