config/routes.rb
Rails.application.routes.draw do
		get 'categories/check_name_present'
		get 'articles/check_name_present'

  devise_for :users
	resources :reviews
	resources :categories
	resources :articles
	get 'say/goodbye'
	get 'say/hello'
	root 'say#hello'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to "Home", say_hello_path, class: "nav-link"%>
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link"%>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" href="/categories">Categories</a>
      </li> -->
      <li class="nav-item dropdown <%= controller.controller_name == 'categories' ? 'active' : ''%>">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
       </a>
       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <% Category.all.each do |category| %>
           <!-- <a class="dropdown-item" href="#">Action</a> -->
           <%= link_to category.name, category, class: 'dropdown-item' %>
         <% end %>
       </div>
     </li>
      <li class="nav-item">
        <% if user_signed_in? %> 
        <!-- welcome <%#= current_user.email %>  -->
        <%= link_to "Account Setting", edit_user_registration_path, class: "nav-link" %><li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        <% else %>
        <%= link_to "Register", new_user_registration_path, class: "nav-link" %><li><%= link_to "Login", new_user_session_path, class: "nav-link" %></li> 
        <% end %>
      </li>
    </ul>
  </div>
</div>
</nav>

<div class="mb-5"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="/javascripts/jquery.js"></script>
    <script src="/javascripts/bootstrap.js"></script>

    <link rel="stylesheet" href="/stylesheets/bootstrap.css" />
    <link rel="stylesheet" href="/stylesheets/blog-home.css" />
  </head>

  <body>
    <%= render "/layouts/nav" %>
    <div class="container">
    <%# if user_signed_in? %> 
      <!-- welcome <%#= current_user.email %>  -->
      <!-- <%#= link_to "Account Setting", edit_user_registration_path %>  | <%#= link_to "Logout", destroy_user_session_path, method: :delete %> |  -->
    <%# else %>
      <!-- <%#= link_to "Register", new_user_registration_path %> | <%#= link_to "Login", new_user_session_path %> |  -->
    <%# end %>
  	<!-- <%#= link_to "Categories", categories_path %> | -->
  	<!-- <%#= link_to "Articles", articles_path%> | -->
  	<!-- <%#= link_to "Home", say_hello_path%> | -->
  	<!-- <%#= link_to "About Us", say_goodbye_path%> | -->
    <!-- <%#= link_to "Google", "http://www.google.com", :target => "_blank"%> | -->
    <!-- <%#= link_to "Gmail", "http://www.gmail.com", :target => "_blank"%> | -->
    <!-- <%#= link_to "DCT", "http://www.dctacademy.com", :target => "_blank"%> | -->
    <%#= link_to "DCT-Assessment", "http://dct-assessment.herokuapp.com", :target => "_blank"%>
  	<br/>
  	<%= notice %>
    <%= alert %>

    <%= yield %>
    </div>

    <%# if user_signed_in? %>
      <!-- <p> You current IP (<%#= current_user.current_sign_in_ip %>) </p> -->
    <%# end %>
  </body>
</html>